model: ollama_chat/qwen2.5-coder:14b
weak-model: ollama_chat/qwen3:4b
edit-format: udiff
no-show-model-warnings: true

# NOTE: aider 0.86.1 treats unknown config keys as pseudo-CLI arguments, so the
# historical `profiles:` mapping now lives in docs/AIDER_PROFILES.yml where it
# can be referenced manually without breaking aider launches.
